[package]
name = "armory_cli"
version = "0.4.0"
edition = "2021"
description = "Cargo workspaces tool"
license = "MIT"

[[bin]]
name = "cargo-armory"
path = "./src/main.rs"

[dependencies]
armory_lib = { version = "0.4.0", path = "../armory_lib" }
dialoguer = "0.10.1"
